#!/usr/bin/env bash

set -e

# turn on autosigning
if [ ! -f /etc/puppet/autosign.conf ]; then
    echo "Enabling certificating autosigning"
    echo "*.lab.local">>/etc/puppet/autosign.conf
fi

# fileserver folder
if [ ! -d /etc/puppet/files ]; then
    mkdir /etc/puppet/files
fi

# allow fileserver access
sed -i /etc/puppet/fileserver.conf -e 's/#  allow 192.168.0.0\/24/allow 192.168.0.0\/24/'

# insert modulepath
sed -i '7i\modulepath=/etc/puppet/modules' /etc/puppet/puppet.conf

# cname for puppet.lab.local
if grep -q "puppet" /etc/bind/zones/db.lab.local
then
    echo "puppet CNAME already present"
else
    echo "adding puppet CNAME"
    echo "puppet          IN      CNAME   wbench" >> /etc/bind/zones/db.lab.local
    service bind9 restart
fi

# copy license files to proper directory
cp -f /var/www/*.lic /etc/puppet/modules/base/files/

# copy topology.dot for ptmd to proper directory
if [ ! -f /etc/puppet/modules/base/files/topology.dot ]; then
    cp /var/www/topology.dot /etc/puppet/modules/base/files/topology.dot
fi

# all ready
service puppetmaster restart

# local puppet agent on the wbench itself
sed -i /etc/default/puppet -e 's/START=no/START=yes/'
service puppet restart

exit 0
