#!/usr/bin/env bash

if [ ! -d /home/cumulus/ansibledemos/roles/common/files ]; then
    mkdir -p /home/cumulus/ansibledemos/roles/common/files
fi

if [ ! -d /home/cumulus/ansibledemos/roles/common/vars ]; then
    mkdir -p /home/cumulus/ansibledemos/roles/common/vars
fi

cp -f /var/www/topology.dot /home/cumulus/ansibledemos/roles/common/files
cp -f /var/www/*.lic /home/cumulus/ansibledemos/roles/common/files

exit 0
