#!/usr/bin/env bash

if [ -f /etc/puppet/autosign.conf ]; then
    rm /etc/puppet/autosign.conf
fi
cp /var/www/topology.dot /etc/puppet/files/topology.dot

if [ -f /var/www/onie-installer ]; then
    rm /var/www/onie-installer
fi
ln -s /var/www/CumulusLinux-2.0.1-powerpc.bin /var/www/onie-installer
