#!/usr/bin/env bash

JSONPATH=""
if [ -f "wbench.json" ]
then
    JSONPATH="wbench.json"
elif [ -f "/var/www/wbench.json" ]
then
    JSONPATH="/var/www/wbench.json"
else
    echo "ERROR: wbench.json not found"
    exit 1
fi

MUXTYPE=$1

if [ "$MUXTYPE" == "overview" ]
then
    clear
    TOPOLOGY=$2
    echo ""
    echo "Cumulus Workbench - Overview"
    echo "----------------------------"
    echo ""
    echo " 'ctrl-b n' to change window/tab "
    echo " 'ctrl-b o' to change pane inside a window "
    echo " 'ctrl-b d' to detach "
    echo ""
    cat $TOPOLOGY.txt
    while :
    do
        read -n1 -r -p " " key
    done
fi

if [ "$MUXTYPE" == "workbench" ]
then
    clear
    echo ""
    echo "Workbench"
    echo ""
fi

if [ "$MUXTYPE" == "switch" ]
then
    SWITCH=$2
    SWCONSRV=`jq -r ".[] | .workbench.switches.$SWITCH.console_server_id" $JSONPATH`
    SWCONPORT=`jq -r ".[] | .workbench.switches.$SWITCH.console_ssh_port" $JSONPATH`
    SWCONUSER=`jq -r ".[] | .workbench.switches.$SWITCH.console_user" $JSONPATH`
    while :
    do
        clear
        echo ""
        echo "Switch: $SWITCH"
        echo ""
        ssh -oStrictHostKeyChecking=no $SWCONUSER@$SWCONSRV -p $SWCONPORT
    done
fi

exit 0
