#!/usr/bin/env bash

SNAME="cw-mux"

# look for wbench.json
JSONPATH=""
if [ -f "wbench.json" ]
then
    JSONPATH="wbench.json"
elif [ -f "/var/www/wbench.json" ]
then
    JSONPATH="/var/www/wbench.json"
else
    echo "ERROR: wbench.json not found"
    exit 1
fi

# grab wbench details
WBENCHID=`jq '.[] | .workbench.wbench_id' $JSONPATH`
WBENCHCLASS=`jq -r '.[] | .workbench.wbench_class' $JSONPATH`
CUSTNAME=`jq -r '.[] | .customer' $JSONPATH`
RESID=`jq '.[] | .id' $JSONPATH`
ENDDATE=(`jq -r '.[] | .end_date' $JSONPATH`)
NUMSWITCHES=`jq -r '.[] | .workbench.switches | length' $JSONPATH`
NUMSERVERS=`jq -r '.[] | .workbench.servers | length' $JSONPATH`

# server might not be running already
tmux start-server

# create session if doesn't already exist
if tmux list-sessions | grep -q "$SNAME:"
then
    echo "Existing session"
    tmux att -d -t cw-mux
    exit 0
else
    echo "No session exists"
    tmux new-session -d -s $SNAME -n Overview
fi

# config the status bar
tmux set-option -t $SNAME status-bg green
tmux set-option -t $SNAME status-fg white
tmux set-window-option -g -t $SNAME window-status-current-bg blue
tmux set-option -t $SNAME base-index 1  # not working
tmux set-option -t $SNAME escape-time 0
tmux set-window-option -t $SNAME aggressive-resize on
tmux set-option -t $SNAME status-left "#[fg=black] WB-$WBENCHID "
tmux set-option -t $SNAME status-right "#[bg=black] $WBENCHCLASS #[bg=cyan] ResID $RESID #[bg=red] Until $ENDDATE     "
 
# workbench
tmux new-window -t $SNAME -n Workbench

# switches
if [ "$NUMSWITCHES" -gt "0" ]
then
    echo "more than 1 switch"
    tmux new-window -t $SNAME -n Switches
fi

# servers
if [ "$NUMSWITCHES" -gt "0" ]
then
    echo "more than 1 servers"
    tmux new-window -t $SNAME -n Servers
fi

tmux select-window -t $SNAME:0

# attach
tmux att -d -t cw-mux

exit 0
