#!/usr/bin/env bash

ln -fs /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer
ln -fs /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer-powerpc
ln -fs /var/www/CumulusLinux-2.1.0-amd64.bin /var/www/onie-installer-x86_64

master_promises="/var/cfengine/masterfiles/promises.cf"

if ! grep 'cldemo.bundles' $master_promises > /dev/null; then
  sed -i 's/      service_catalogue,/      service_catalogue,\n                          \"cldemo\",\n                          @(cldemo.bundles),\n/' $master_promises
fi

if ! grep 'cldemo.promise_files' $master_promises >/dev/null; then
  sed -i 's!      "services/file_change.cf",!      "services/file_change.cf",\n                  "cldemo/promises.cf",\n                  @(cldemo.promise_files),!' $master_promises
fi

exit 0
