#!/usr/bin/env bash

pushd /usr/local/share/chef
	knife node from file nodes/leaf1.json
	knife node from file nodes/leaf2.json

	pushd data_bags
		knife data bag from file interfaces interfaces
	popd

exit 0

