#!/usr/bin/env bash

set -e

VPNUSER="cumulus"
USERGROUP="cumulus"
VPNNAME="wbenchvpn"
TBLKDIR="/home/$VPNUSER/$VPNNAME.tblk"
CONFDIR="/etc/openvpn"

echo "AUTOSTART=\"all\"" >> /etc/default/openvpn

# copy easy-rsa for server CA creation
if [ ! -f $CONFDIR/$VPNNAME.key ]; then
    mkdir $CONFDIR/easy-rsa/
    cp -r /usr/share/doc/openvpn/examples/easy-rsa/2.0/* $CONFDIR/easy-rsa/
fi

# CA variables
export EASY_RSA="/etc/openvpn/easy-rsa"

echo "
export EASY_RSA=$EASY_RSA
export OPENSSL=\"openssl\"
export PKCS11TOOL=\"pkcs11-tool\"
export GREP=\"grep\"
export KEY_CONFIG=\`$EASY_RSA/whichopensslcnf $EASY_RSA\`
export KEY_DIR=\"$EASY_RSA/keys\"
export KEY_SIZE=1024
export CA_EXPIRE=3650
export KEY_EXPIRE=3650
export KEY_COUNTRY=\"US\"
export KEY_PROVINCE=\"CA\"
export KEY_CITY=\"MountainView\"
export KEY_ORG=\"Cumulus-Networks\"
export KEY_EMAIL=\"mail@cumulusnetworks.com\"
export KEY_CN=workbench
export KEY_NAME=workbench-key
export KEY_OU=workbench
export PKCS11_MODULE_PATH=changeme
export PKCS11_PIN=1234
" > $CONFDIR/easy-rsa/vars

#generate CA
source $CONFDIR/easy-rsa/vars
$CONFDIR/easy-rsa/clean-all
$CONFDIR/easy-rsa/build-ca --batch

# build server keys
$CONFDIR/easy-rsa/build-key-server --batch workbench

# generate Diffie Hellman parameters
$CONFDIR/easy-rsa/build-dh

# generate secret
if [ ! -f $CONFDIR/$VPNNAME.key ]; then
    /usr/sbin/openvpn --genkey --secret $CONFDIR/$VPNNAME.key
fi

# create tunnelblick config
if [ ! -d $TBLKDIR ]; then
    mkdir $TBLKDIR
fi

# setting CA variables again to change KEY_CN and KEY_NAME
echo "
export EASY_RSA=$EASY_RSA
export OPENSSL=\"openssl\"
export PKCS11TOOL=\"pkcs11-tool\"
export GREP=\"grep\"
export KEY_CONFIG=\`$EASY_RSA/whichopensslcnf $EASY_RSA\`
export KEY_DIR=\"$EASY_RSA/keys\"
export KEY_SIZE=1024
export CA_EXPIRE=3650
export KEY_EXPIRE=3650
export KEY_COUNTRY=\"US\"
export KEY_PROVINCE=\"CA\"
export KEY_CITY=\"MountainView\"
export KEY_ORG=\"Cumulus-Networks\"
export KEY_EMAIL=\"mail@cumulusnetworks.com\"
export KEY_CN=wbench
export KEY_NAME=wbench_key
export KEY_OU=workbench
export PKCS11_MODULE_PATH=changeme
export PKCS11_PIN=1234
" > $CONFDIR/easy-rsa/vars

#generate CA
source $CONFDIR/easy-rsa/vars

/etc/openvpn/easy-rsa/build-key --batch wbench1

# copy the key into the client package
cp -f $CONFDIR/easy-rsa/keys/wbench1.key $TBLKDIR/wbench1.key
cp -f $CONFDIR/easy-rsa/keys/wbench1.crt $TBLKDIR/wbench1.crt
cp -f $CONFDIR/easy-rsa/keys/ca.crt $TBLKDIR/ca.crt

echo "
dev tun1
port 9999
proto tcp-server
comp-lzo
ca $CONFDIR/easy-rsa/keys/ca.crt
cert $CONFDIR/easy-rsa/keys/workbench.crt
key $CONFDIR/easy-rsa/keys/workbench.key
dh $CONFDIR/easy-rsa/keys/dh1024.pem
server 172.16.24.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push \"route 192.168.0.0 255.255.255.0\"
keepalive 10 120
" > $CONFDIR/server.conf

# while true; do
#     read -p "Please enter your workbench number: " WBENCH
#     case $WBENCH in 
#         [0-9][0-9][0-9]) break;;
#  	* ) echo "Invalid wbench number";;
#     esac
# done

WBENCH_PORT=`cat /var/www/wbench.json | jq '.[] | .workbench.external_tcp_port'`

echo "
dev tun1
client
tls-client
proto tcp-client
comp-lzo
remote 216.129.126.114 $WBENCH_PORT
ca ca.crt
cert wbench1.crt
key wbench1.key
keepalive 10 120
" > $TBLKDIR/client.conf

chown -R $VPNUSER:$USERGROUP $TBLKDIR

echo "***"
echo "TunnelBlick config available: $TBLKDIR"
echo "***"

service openvpn start

# hide autoindex icons as they try to move up the directory chain
sed -i 's/Add/# Add/' /etc/apache2/mods-available/autoindex.conf

service apache2 restart

exit 0
