#!/usr/bin/env bash

#echo "Configuring apt-mirror for Cumulus repos"

if [ -e /etc/apt/mirror.list ]
  then
    rm /etc/apt/mirror.list
fi

cp /etc/apt/mirror.list.cumulus /etc/apt/mirror.list

# /etc/apache2/conf.d/local repo copied over as part of the package with /dists/ + /pool/ in
apache2ctl restart

# sync the mirror
apt-mirror
