interfaces:
  spine1:
    loopback: "10.2.1.3"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.2/30"
      swp2:
        ip_and_mask: "10.1.1.6/30"
      swp3:
        ip_and_mask: "10.1.1.10/30"
      swp4:
        ip_and_mask: "10.1.1.14/30"
      swp17:
        ip_and_mask: "10.1.1.50/30"
      swp18:
        ip_and_mask: "10.1.1.54/30"
      swp19:
        ip_and_mask: "10.1.1.58/30"
      swp20:
        ip_and_mask: "10.1.1.62/30"
  spine2:
    loopback: "10.2.1.4"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.18/30"
      swp2:
        ip_and_mask: "10.1.1.22/30"
      swp3:
        ip_and_mask: "10.1.1.26/30"
      swp4:
        ip_and_mask: "10.1.1.30/30"
      swp17:
        ip_and_mask: "10.1.1.34/30"
      swp18:
        ip_and_mask: "10.1.1.38/30"
      swp19:
        ip_and_mask: "10.1.1.42/30"
      swp20:
        ip_and_mask: "10.1.1.46/30"
  leaf1:
    loopback: "10.2.1.1"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.1/30"
      swp2:
        ip_and_mask: "10.1.1.5/30"
      swp3:
        ip_and_mask: "10.1.1.9/30"
      swp4:
        ip_and_mask: "10.1.1.13/30"
      swp17:
        ip_and_mask: "10.1.1.33/30"
      swp18:
        ip_and_mask: "10.1.1.37/30"
      swp19:
        ip_and_mask: "10.1.1.41/30"
      swp20:
        ip_and_mask: "10.1.1.45/30"
    bridges:
      br0:
        ip_and_mask: "10.4.1.1/25"
        members: ["swp30","swp31","swp32","swp33"]
      br1:
        ip_and_mask: "10.4.1.129/25"
        members: ["swp34","swp35","swp36","swp37"]
  leaf2:
    loopback: "10.2.1.2"
    int_numbered:
      swp1:
        ip_and_mask: "10.1.1.17/30"
      swp2:
        ip_and_mask: "10.1.1.21/30"
      swp3:
        ip_and_mask: "10.1.1.25/30"
      swp4:
        ip_and_mask: "10.1.1.29/30"
      swp17:
        ip_and_mask: "10.1.1.49/30"
      swp18:
        ip_and_mask: "10.1.1.53/30"
      swp19:
        ip_and_mask: "10.1.1.57/30"
      swp20:
        ip_and_mask: "10.1.1.61/30"
    bridges:
      br0:
        ip_and_mask: "10.4.2.1/25"
        members: ["swp30","swp31","swp32","swp33"]
      br1:
        ip_and_mask: "10.4.2.129/25"
        members: ["swp34","swp35","swp36","swp37"]

hostnetranges:
  - 10.4.0.0/16

bgp:
  spine1:
    myasn: 65000
    peergroupv4:
      leafs:
        peerasn: 65000
        peers: ["10.1.1.1","10.1.1.5","10.1.1.9","10.1.1.13","10.1.1.49","10.1.1.53","10.1.1.57","10.1.1.61"]
        routereflectorclient: True
  spine2:
    myasn: 65000
    peergroupv4:
      leafs:
        peerasn: 65000
        peers: ["10.1.1.17","10.1.1.21","10.1.1.25","10.1.1.29","10.1.1.33","10.1.1.37","10.1.1.41","10.1.1.45"]
        routereflectorclient: True
  leaf1:
    myasn: 65000
    peergroupv4:
      spines:
        peerasn: 65000
        peers: ["10.1.1.2","10.1.1.6","10.1.1.10","10.1.1.14","10.1.1.34","10.1.1.38","10.1.1.42","10.1.1.46"]
  leaf2:
    myasn: 65000
    peergroupv4:
      spines:
        peerasn: 65000
        peers: ["10.1.1.18","10.1.1.22","10.1.1.26","10.1.1.30","10.1.1.50","10.1.1.54","10.1.1.58","10.1.1.62"]
