#!/usr/bin/env bash

ln -fs /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer
ln -fs /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer-powerpc
ln -fs /var/www/CumulusLinux-2.1.0-amd64.bin /var/www/onie-installer-x86_64

knife cookbook upload cldemo_ospf_unnumbered

pushd /usr/local/share/chef/data_bags
	knife data bag from file interfaces interfaces
popd

exit 0
