#!/usr/bin/env bash



# Install puppet at the end of the host Ubuntu install

cat <<EOF >>/var/www/ubuntu-kickstart/ks.cfg

%post
apt-get -q -y update
apt-get -q -y upgrade
apt-get -q -y install puppet
sed -i /etc/default/puppet -e 's/START=no/START=yes/'
service puppet restart
%end
EOF


# Trigger OS installation on hosts
cw-pxehelper -s server1 -o ubuntuserver-precise -n
cw-pxehelper -s server2 -o ubuntuserver-precise -n


exit 0
