#!/usr/bin/env bash

umask 077
cp /var/cfengine/masterfiles/update.cf /var/cfengine/masterfiles/failsafe.cf


# bootstrap the host to the policy server
/var/cfengine/bin/cf-agent --bootstrap 192.168.0.1

exit 0
