#!/usr/bin/env bash

failsafe="/var/cfengine/masterfiles/update.cf"

umask 077
if [[ ! -f $failsafe ]]; then
  cp /var/cfengine/masterfiles/update.cf $failsafe
fi

# bootstrap the host to the policy server
if [[ ! -f /var/cfengine/inputs/promises.cf ]]; then
  /var/cfengine/bin/cf-agent --bootstrap 192.168.0.1
fi

exit 0
