#!/usr/bin/env bash

if [ -f /var/www/onie-installer ]; then
    rm /var/www/onie-installer
fi
if [ -f /var/www/onie-installer-powerpc ]; then
    rm /var/www/onie-installer-powerpc
fi
if [ -f /var/www/onie-installer-x86_64 ]; then
    rm /var/www/onie-installer-x86_64
fi

ln -s /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer
ln -s /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer-powerpc
ln -s /var/www/CumulusLinux-2.1.0-amd64.bin /var/www/onie-installer-x86_64

if ! grep 'cldemo.bundles' $master_promises > /dev/null; then
  sed -i 's/      service_catalogue,/      service_catalogue,\n                          \"cldemo\",\n                          @(cldemo.bundles),\n/' $master_promises
fi

if ! grep 'cldemo.promise_files' $master_promises >/dev/null; then
  sed -i 's!      "services/file_change.cf",!      "services/file_change.cf",\n                  "cldemo/promises.cf",\n                  @(cldemo.promise_files),!' $master_promises
fi

exit 0
