#!/usr/bin/env bash

cp /var/www/topology.dot /etc/puppet/modules/ibgp/files/topology.dot

if [ -f /var/www/onie-installer ]; then
    rm /var/www/onie-installer
fi
if [ -f /var/www/onie-installer-powerpc ]; then
    rm /var/www/onie-installer-powerpc
fi
if [ -f /var/www/onie-installer-x86_64 ]; then
    rm /var/www/onie-installer-x86_64
fi

ln -s /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer
ln -s /var/www/CumulusLinux-2.1.0-powerpc.bin /var/www/onie-installer-powerpc
ln -s /var/www/CumulusLinux-2.1.0-amd64.bin /var/www/onie-installer-x86_64

exit 0
