#!/usr/bin/env bash

# turn on autosigning
if [ ! -f /etc/puppet/autosign.conf ]; then
    echo "Enabling certificating autosigning"
    echo "*.lab.local">>/etc/puppet/autosign.conf
fi

# fileserver folder
if [ ! -d /etc/puppet/files ]; then
    mkdir /etc/puppet/files
fi

# allow fileserver access
sed -i /etc/puppet/fileserver.conf -e 's/#  allow 192.168.0.0\/24/allow 192.168.0.0\/24/'

# cname for puppet.lab.local
if grep -q "puppet" /etc/bind/zones/db.lab.local
then
    echo "puppet CNAME already present"
else
    echo "adding puppet CNAME"
    echo "puppet          IN      CNAME   wbench" >> /etc/bind/zones/db.lab.local
    service bind9 restart
fi

# all ready
service puppetmaster restart
