#!/usr/bin/env bash

# turn on autosigning
if [ ! -f /etc/puppet/autosign.conf ]; then
    echo "*.lab.local" > /etc/puppet/autosign.conf
fi

# fileserver folder
if [ ! -d /etc/puppet/files ]; then
    mkdir /etc/puppet/files
fi

# allow fileserver access
sed -i /etc/puppet/fileserver.conf -e 's/#  allow 192.168.0.0\/24/allow 192.168.0.0\/24/'

# all ready
service puppetmaster restart
