#!/usr/bin/env bash

if [ -f /var/www/onie-installer ]; then
    rm /var/www/onie-installer
fi
ln -s /var/www/CumulusLinux-2.0.2-powerpc.bin /var/www/onie-installer

cp -f /var/www/*.lic /home/cumulus/ansibledemos/ospfunnum-2s/roles/cumulus/files

exit 0
