#!/usr/bin/env bash

ISOURL=http://mirror.cwb.cumulusnetworks.com/vmware/VMware-VMvisor-Installer-5.5.0.update01-1623387.x86_64.iso
ISOMD5SUM=36dfcb269a20d7bfe7323f825128e1a8
ISOTMP=/tmp/vmware-esxi.iso
ISOMNT=/mnt/esxicd
PXEDIR=/var/lib/tftpboot/pxe
ESXDIR=esxi55
BOOTCFG=$PXEDIR/$ESXDIR/boot.cfg

# download esxi iso
if [ -f $ISOTMP ]; then
	rm $ISOTMP
fi
wget $ISOURL -O $ISOTMP

# check md5sum
DOWNLOADMD5SUM=($(md5sum $ISOTMP))
if [ "$DOWNLOADMD5SUM" != "$ISOMD5SUM" ]; then
    echo "** ESXi MD5 do not match:"
    echo "** Download $DOWNLOADMD5SUM"
    echo "** Expected $ISOMD5SUM"
    exit 1
fi

# folder for esxi installer
if [ -d $PXEDIR/$ESXDIR ]; then
    rm -rf $PXEDIR/$ESXDIR
fi
mkdir -p $PXEDIR/$ESXDIR

# extract iso
echo "Extracting ESXi CD"
mkdir -p $ISOMNT
mount -o loop,ro $ISOTMP $ISOMNT
rsync -a $ISOMNT/ $PXEDIR/$ESXDIR/
umount $ISOMNT
echo "Extract complete"

# edit ESXi boot.cfg

# remove slashes
sed -i $BOOTCFG -e "s#/##g"

# add prefix
echo "prefix=$ESXDIR/" >> $BOOTCFG

# change title
sed -i $BOOTCFG -e "s#Loading ESXi installer#Loading Cumulus CW ESXi installer#g"

echo *****************************************************
echo Workbench host OS package: VMWare ESXi 5.5
echo
echo OS install files have been added to /var/lib/tftpboot
echo You can install an OS on a host using:
echo
echo $ cw-pxehelper -s server1 -o esxi55 -n
echo
echo *****************************************************

exit 0
