#!/usr/bin/env bash

PXEDIR=/var/lib/tftpboot/pxe
UBDIR=ubuntu-installer
NETBOOTURL=http://archive.ubuntu.com/ubuntu/dists/precise-updates/main/installer-amd64/current/images/netboot/ubuntu-installer

# folder for esxi installer
if [ -d $PXEDIR/$UBDIR ]; then
    rm -rf $PXEDIR/$UBDIR
fi
mkdir -p $PXEDIR/$UBDIR

# mirror netboot content
lftp -c "open $NETBOOTURL; mirror . $PXEDIR/$UBDIR"

echo *****************************************************
echo Workbench host OS package: Ubuntu Server
echo
echo OS install files have been added to /var/lib/tftpboot
echo You can install an OS on a host using:
echo
echo $ cw-pxehelper -s server1 -o ubuntuserver -n
echo
echo *****************************************************

exit 0

