#!/bin/bash
if [ -e /usr/bin/ovs-vsctl ]; 
  then update-rc.d sflowovsd defaults; 
fi 
echo "
_sflow._udp     30      SRV     0 0 6343 wbench
_sflow._udp     30      TXT     (
"txtvers=1"
"sampling.1G=64"
"polling=10"
) " >> /etc/bind/zones/db.lab.local
service bind9 restart

update-rc.d sflow-rt defaults
#/etc/init.d/sflow-rt restart
a2enmod proxy_html
# a2enconf /var/www/sflow-rt-cumulus/sflow-rt.conf
ln -s /var/www/sflow-rt/sflow-rt.conf /etc/apache2/conf.d/sflow-rt.conf
/etc/init.d/apache2 reload

exit 0
