#!/usr/bin/env bash

SYSLINUX_SRC=https://www.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.tar.gz
SYSLINUX_TMP=/tmp/syslinux-3.86.tar.gz
SYSLINUX_DIR=syslinux-3.86
PXEDIR=/var/lib/tftpboot/pxe
DHCPPOOL=/etc/dhcpd/dhcpd.pools

mkdir -p $PXEDIR

# download syslinux
if [ -f $SYSLINUX_TMP ]; then
    rm $SYSLINUX_TMP
fi
wget -O $SYSLINUX_TMP $SYSLINUX_SRC

# extract pxelinux.0, menu.c32 and chain.c32
tar --no-same-permissions --no-same-owner --strip-components 2 -xzf $SYSLINUX_TMP -C $PXEDIR $SYSLINUX_DIR/core/pxelinux.0
tar --no-same-permissions --no-same-owner --strip-components 3 -xzf $SYSLINUX_TMP -C $PXEDIR $SYSLINUX_DIR/com32/menu/menu.c32 $SYSLINUX_DIR/com32/modules/chain.c32

mkdir -p $PXEDIR/pxelinux.cfg

# default to local hdd, tftp-hpa doesn't follow symlinks :(
cp -rf $PXEDIR/pxelinux.cfg/cfg-localhdd $PXEDIR/pxelinux.cfg/default

# add PXE elements to dhcpd config
if ! grep --quiet "next-server" $DHCPPOOL; then
    sed -i $DHCPPOOL -e 's/option routers 192.168.0.1;/option routers 192.168.0.1;\
  next-server 192.168.0.1;/g'
fi
if ! grep --quiet "pxe/pxelinux.0" $DHCPPOOL; then
    sed -i $DHCPPOOL -e 's/option routers 192.168.0.1;/option routers 192.168.0.1;\
  filename = "pxe\/pxelinux.0";/g'
fi
service isc-dhcp-server restart

exit 0
