#!/usr/bin/env bash

if [ -f /var/www/onie-installer ]; then
    rm /var/www/onie-installer
fi
ln -s /var/www/CumulusLinux-2.0.1-powerpc.bin /var/www/onie-installer

if [ ! -s /home/cumulus/ansibledemos/ospfunnum-2s2l/roles/cumulus/files/license.txt ]; then
    echo "***"
    echo "*** Non EULA license must be placed in /home/cumulus/ansibledemos/ospfunnum-2s2l/roles/cumulus/files/license.txt  ***"
    echo "***"
fi

exit 0
